### ISSUE TITLE
UnicodeDecodeError:

### ISSUE THREAD

**Issue by zeeebbbrrraaa** [graysuit/facebrute#1]
Traceback (most recent call last):                                         
  File "fb.py", line 18, in <module>                                       
    for line in open(wlist,'r'):                                           
  File "/usr/lib/python3.7/codecs.py", line 322, in decode                 
    (result, consumed) = self._buffer_decode(data, self.errors, final)     
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte

**Comment by graysuit** [comment]
Check your **password** list,
I think your **password** list contains some Unicode characters,
Use <a href="https://github.com/graysuit/wGen">**WGEN**<a/> to generate password list.

You are at stage where Duplicate **passwords** and **passwords** under 6 length are removed,
If you want **you can remove these lines,**
From line **16 To 24** in fb.py.

**Comment by graysuit** [comment]
No activity after 26 days,
So I am closing this issue,
Open this again if you want
